name: Build Aurum Plugin

on:
  push:
    branches: '*'
    tags-ignore: '*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
              10.x.x
              9.x.x
      - name: Restore dependencies
        run: dotnet restore .\Aurum\Aurum.csproj
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
      - name: Build
        run: |
          dotnet build .\Aurum\Aurum.csproj --no-restore --configuration Release --nologo
      - name: Archive
        run: Compress-Archive -Path Aurum/bin/Release/* -DestinationPath Aurum.zip
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./Aurum/bin/Release/*
